export { default as Main } from './Main'
export { default as About} from './About'
export { default as Services} from './Services'
export { default as ServiceDetail} from './ServiceDetail'
export { default as Faq} from './Faq'
export { default as Contact} from './Contact'
export { default as Testimonials} from './Testimonials'